---
- name: checking os version 
  hosts: all
  remote_user: zpc
  become: yes
  become_user: hadmin
  tasks:
  - name: checking uptime for OEL 6
    command: uptime
    when: ansible_distribution=='OracleLinux' and ansible_distribution_major_version=='6'
    register: uptime
  - debug:
     var: uptime.stdout
  - name: Checking uptime for OEL 7
    command: uptime
    when: ansible_distribution=='OracleLinux' and ansible_distribution_major_version=='7'
    register: uptime
  - debug:
     var: uptime.stdout
  - name: Checking uptime for RHEL
    command: uptime
    when: ansible_distribution=='RedHat' and ansible_distribution_major_version=='7'
    register: uptime
  - debug:
     var: uptime.stdout

