---
- name: Replace yumrepo file
  hosts: all
  remote_user: zpc
  become: yes
  tasks:
   
  - name: Replace yumrepo file
    ansible.builtin.copy:
      src: /home/ansible/lh175641/uek-ol7.repo
      dest: /etc/yum.repos.d/uek-ol7.repo
    when: ansible_distribution=='OracleLinux' and ansible_distribution_major_version=='7'
 
          
...
