---
- name: checking process
  hosts: all
  remote_user: zpc
  become: yes
  become_user: hadmin
  tasks: 
  - name: Checking the running processess
    command: uptime
    register: uptime
  - debug:
     var: uptime.stdout
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
...
  
